spring:
  application:
    name: ai-agent
  ai:
    dashscope:
      api-key: sk-9281894fcc7a46ebb8ea3a5e9ea3c976
      chat:
        options:
          model: tongyi-xiaomi-analysis-pro
server:
  port: 8888
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: cn.kplusone.aiagent.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
